baseURL = "https://rithinnagaraj.github.io/"
languageCode = "en-us"
title = "Rin's Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      math = true
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  style = "dracula"